### ISSUE TITLE
dist - Mac OSX binaries

### ISSUE THREAD

**Issue by TeaM-TL** [TeaM-TL/FotoKilof#15]

**Comment by TeaM-TL** [comment]
PYPI or zip package are enough

**Comment by steveruizok** [comment]
To expand on this answer, to get this running on your Mac:

- Download the Linux release (ends in `.whl`).
- Open the Terminal app, then navigate to your downloads folder (`cd Downloads`).
- Type `python3 FotoKilof-3.4.0-py3-none-any.whl/src` and press Enter.

If you have trouble, it may be due to an older version of Python on your computer. (This will work on most Macs, however, as Python comes with the operating system). If in doubt, Google for instructions on how to install the latest Python on your machine.

P.S. This is a great app! If possible, I'd love to see an OSX app shipped in future releases. The above steps might be too technical for most users.
