### ISSUE TITLE
Add dithering options

### ISSUE THREAD

**Issue by gingerbeardman** [TeaM-TL/FotoKilof#84]
**Is your feature request related to a problem? Please describe.**

- currently I have to use custom to do dithering of the image

the order of processing needs to be

1. black & white
1. scaling
1. dithering, eg. `-ordered-dither o2x2`

**Describe the solution you'd like**

- new option for dithering

**Describe alternatives you've considered**

- custom

**Additional context**

- https://legacy.imagemagick.org/Usage/quantize/#ordered-dither

**Comment by TeaM-TL** [comment]
I don't want to add more and more conversion method, because it will is way to implement every options of ImageMagick.
I think, that the best way is use Custom box as you use now.
I have an idea to save favorite custom commands, and use it from list. It means you can store your favorite commands and use it everytime from history
